#!/bin/sh
## this script pushes a Play application into production
## this assumes the following
## * you staged the application using sbt
## * the server was set up using the Puppet class play::app

if [ -z "$1" ]; then
    echo "Usage: $0 server"
    return 1
fi

SERVER="$1"
APP="vs"

cd `dirname $0`

APP_VERSION=$(git rev-parse --short HEAD)
echo "Staging $APP $APP_VERSION"

# note: the trailing slash is important
STAGING_AREA="/usr/local/play/staging-area/$APP/"
APP_DIRECTORY="${STAGING_AREA}${APP_VERSION}/"
TEMP="${STAGING_AREA}temp/"

# make sure that all directories exist
ssh "root@${SERVER}" "mkdir -p ${TEMP} ${APP_DIRECTORY}"

# use $temp as the first target so that we may avoid uploading the
# same files again
rsync -zr --delete target/staged "root@${SERVER}:${TEMP}"
rsync -zr --exclude '*~' --delete conf "root@${SERVER}:${TEMP}"

# finally stage the application under its git version-aware directory
ssh "root@${SERVER}" "cp -r ${TEMP}/* ${APP_DIRECTORY}"
